version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - cd examples/userpool
      - yarn
  pre_build:
    commands:
      - yarn bootstrap
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - yarn deploy
